// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVMhq_KN14Drtwwf4NfnjDqS1Lhpn4wak',
    appId: '1:465862068014:web:0a305e841a379c29041cbf',
    messagingSenderId: '465862068014',
    projectId: 'labour-services-a081c',
    authDomain: 'labour-services-a081c.firebaseapp.com',
    storageBucket: 'labour-services-a081c.firebasestorage.app',
    measurementId: 'G-WNK771SDKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpngy7c1BQvhk5-77ChiyAsK83d6-to_8',
    appId: '1:465862068014:android:d1511de761461f4b041cbf',
    messagingSenderId: '465862068014',
    projectId: 'labour-services-a081c',
    storageBucket: 'labour-services-a081c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ1qQ4sXyertrU_DC4WhdhGzC62QTRhhU',
    appId: '1:465862068014:ios:e25490f040e8d510041cbf',
    messagingSenderId: '465862068014',
    projectId: 'labour-services-a081c',
    storageBucket: 'labour-services-a081c.firebasestorage.app',
    androidClientId: '465862068014-n2qguunt8voj7nt52uuscsqafp0sqo5q.apps.googleusercontent.com',
    iosClientId: '465862068014-b350nhfk4t7el9eve7dhu8rdfcr64ilk.apps.googleusercontent.com',
    iosBundleId: 'com.techease.asifTaj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ1qQ4sXyertrU_DC4WhdhGzC62QTRhhU',
    appId: '1:465862068014:ios:e25490f040e8d510041cbf',
    messagingSenderId: '465862068014',
    projectId: 'labour-services-a081c',
    storageBucket: 'labour-services-a081c.firebasestorage.app',
    androidClientId: '465862068014-n2qguunt8voj7nt52uuscsqafp0sqo5q.apps.googleusercontent.com',
    iosClientId: '465862068014-b350nhfk4t7el9eve7dhu8rdfcr64ilk.apps.googleusercontent.com',
    iosBundleId: 'com.techease.asifTaj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpYEGwLF0AeJVYu4pyCKEYUGxwA3MfA80',
    appId: '1:465862068014:web:414e986a8278e16a041cbf',
    messagingSenderId: '465862068014',
    projectId: 'labour-services-a081c',
    authDomain: 'labour-services-a081c.firebaseapp.com',
    storageBucket: 'labour-services-a081c.firebasestorage.app',
    measurementId: 'G-K4JVYSY7H5',
  );
}
